### ISSUE TITLE
The given alias '`tx_t3monitoring_domain_model_extension`' is not unique in FROM and JOIN clause table.

### ISSUE THREAD

**Issue by bihor** [georgringer/t3monitoring#134]
I have updated the extension from version 1 to 2 and when I save an client-entry I get now this error message:

Oops, an error occurred!
The given alias '`tx_t3monitoring_domain_model_extension`' is not unique in FROM and JOIN clause table. The currently registered aliases are: `tx_t3monitoring_client_extension_mm`, `tx_t3monitoring_domain_model_extension`.

**Comment by AureliusHogan** [comment]
Same here in a fresh installation of TYPO3 9.3.3, PHP 7.2.7 and MySQL 5.5.59. Everything works fine until I create a second client.

**Comment by AureliusHogan** [comment]
Just got the current master. Everything is fine with that one.

**Comment by ursbraem** [comment]
> Just got the current master

For everybody who doesn't know how to: in composer.json, it must be 

`"t3monitor/t3monitoring": "dev-master"`

instead of 

`"t3monitor/t3monitoring": "^2.0"`

to achieve this, composer.json can be edited manually (not recommended) or `composer req t3monitor/t3monitoring:dev-master`

-> the "dev-" prefix just means: look at branches, not at tags.
